//settings
export const EDIT_DESIGN = 'EDIT_DESIGN'
//widgets
export const SAVE_NEW_WIDGET = 'SAVE_NEW_WIDGET'
export const UPDATE_WIDGET = 'UPDATE_WIDGET'
export const DELETE_WIDGET = 'DELETE_WIDGET'
//users
export const ADMIN_GET_USERS ='ADMIN_GET_USERS'
export const ADMIN_GET_USER ='ADMIN_GET_USER'
//metas
export const ADMIN_GET_META='ADMIN_GET_META'
export const ADMIN_GET_METAS='ADMIN_GET_METAS'
export const ADMIN_EDIT_META = 'ADMIN_EDIT_META'
export const ADMIN_UPDATE_META = 'ADMIN_UPDATE_META'
//posts
export const ADMIN_GET_POSTS ='ADMIN_GET_POSTS'
export const ADMIN_SET_TOTAL_COUNT ='ADMIN_SET_TOTAL_COUNT'
export const ADMIN_GET_POST = 'ADMIN_GET_POST'
export const ADMIN_EDIT_POST = 'ADMIN_EDIT_POST'
//comments
export const ADMIN_GET_COMMENTS='ADMIN_GET_COMMENTS'
export const ADMIN_GET_COMMENT='ADMIN_GET_COMMENT'
export const ADMIN_DELETE_COMMENT='ADMIN_DELETE_COMMENT'
export const ADMIN_EDIT_COMMENT='ADMIN_EDIT_COMMENT'
//forms
export const ADMIN_GET_FORMS='ADMIN_GET_FORMS'
export const ADMIN_GET_FORM='ADMIN_GET_FORM'
//orders
export const ADMIN_GET_ORDERS='ADMIN_GET_ORDERS'
export const ADMIN_GET_ORDER='ADMIN_GET_ORDER'
export const ADMIN_DELETE_ORDER='ADMIN_DELETE_ORDER'
export const ADMIN_EDIT_ORDER='ADMIN_EDIT_ORDER'
//pages
export const GET_CUSTOM_PAGES = 'GET_CUSTOM_PAGES'
export const ADMIN_GET_PAGES = 'ADMIN_GET_PAGES'
export const ADMIN_GET_PAGE = 'ADMIN_GET_PAGE'
export const ADMIN_EDIT_PAGE_FIELD = 'ADMIN_EDIT_PAGE_FIELD'
export const ADMIN_UPDATE_PAGE = 'ADMIN_EDIT_PAGE_FIELD'
export const ADMIN_SAVE_NEW_PAGE = 'ADMIN_EDIT_PAGE_FIELD'
//generals
export const SET_SIDEBAR_STATUS = 'SET_SIDEBAR_STATUS'
export const SERVER_LOG = 'SERVER_LOG'
//terminal Actions
export const TERMINA_LOG = 'TERMINA_LOG'
export const EXECUTE_COMMAND = 'EXECUTE_COMMAND'


