export const INITIAL_POSTS = 'INITIAL_POSTS'
//USER TYPES
export const USER_AUTO_LOGIN ='USER_AUTO_LOGIN'
export const USER_LOGIN ='USER_LOGIN'
export const USER_LOGOUT ='USER_LOGOUT'
export const USER_REGISTER ='USER_REGISTER'
export const GET_SPECIFIC_USER_DATA ='GET_SPECIFIC_USER_DATA'
export const DISPATCH_SOCKET_ID ='SET_SOCKET_ID'
export const RESET_PASSWORD ='RESET_PASSWORD'
export const UPDATE_USER_DATA_FIELD ='UPDATE_USER_DATA_FIELD'

//messenger
export const GET_CONVERSATIONS ='GET_CONVERSATIONS'
export const GET_CONVERSATION ='GET_CONVERSATION'
export const DELETE_CONVERSATION ='GET_CONVERSATION'
export const NEW_MESSAGE_IN_CONVERSATION ='NEW_MESSAGE_IN_CONVERSATION'
//call
export const SET_CALLING_STATUS ='SET_CALLING_STATUS'
export const SET_PARTNER_VIDEO ='SET_PARTNER_VIDEO'
export const SET_MY_VIDEO ='SET_MY_VIDEO'
export const SET_CALL_ACCEPTED ='SET_CALL_ACCEPTED'
export const INCOMING_CALL ='INCOMING_CALL'
export const OUTGOING_CALL ='OUTGOING_CALL'
export const END_CALL ='END_CALL'
//user page
export const SET_USER_PAGE_DATA= 'SET_USER_PAGE_DATA'
export const GET_USER_PAGE_DATA= 'GET_USER_PAGE_DATA'
//WIDGETS TYPES
export const GET_WIDGETS ='GET_WIDGETS'
export const SET_WIDGETS ='SET_WIDGETS'
export const SET_WIDGETS_IN_GROUPS ='SET_WIDGETS_IN_GROUPS'
// export const SET_WIDGETS_FOR_ADMIN ='SET_WIDGETS_FOR_ADMIN'
//GLOBAL STATE TYPES
export const SET_HEAD_DATA = 'SET_HEAD_DATA'
export const LOGIN_REGISTER_FORM ='LOGIN_REGISTER_FORM'
export const LOADING ='LOADING'
export const SET_NOT_FOUND_PAGE ='SET_NOT_FOUND_PAGE'
export const SET_ALERT ='SET_ALERT'
export const CLOSE_ALERT ='CLOSE_ALERT'
export const CHECK_ROUTE_AND_SET_LOADING= 'CHECK_ROUTE_AND_SET_LOADING'
export const HYDRATE ='HYDRATE'
//SETTINGS TYPES
export const GET_SETTINGS ='GET_SETTINGS'
export const SET_SETTINGS ='SET_SETTINGS'
//POSTS TYPES
export const GET_POSTS = 'GET_POSTS'
export const GET_POST = 'GET_POST'
export const GET_EDITING_POST = 'GET_EDITING_POST'
export const EDIT_POST_FIELD = 'EDIT_POST_FIELD'
export const SET_POST = 'SET_POST'
export const LIKE_POST ='LIKE_POST'
export const DISLIKE_POST ='DISLIKE_POST'
export const VIEW_POST ='VIEW_POST'
//comments
export const GET_COMMENTS = 'GET_COMMENTS'
// export const GET_COMMENT = 'GET_COMMENT'
export const NEW_COMMENT = 'NEW_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
//metas
export const SET_CATEGORIES_METAS = 'SET_CATEGORIES_METAS'
export const SET_TAGS_METAS = 'SET_TAGS_METAS'
export const SET_ACTORS_METAS = 'SET_ACTORS_METAS'
export const GET_METAS = 'GET_METAS'

//CHATROOM ACTIONS TYPES
export const SET_ONLINE_USERS = 'SET_ONLINE_USERS'
export const SET_MESSAGES = 'SET_MESSAGES'
export const NEW_MESSAGE = 'NEW_MESSAGE'
export const SET_ACTIVE_VISIBLE_PROFILE = 'SET_ACTIVE_VISIBLE_PROFILE'
//POSTS PAGES TYPES
export const SET_POSTS_DATA = 'SET_POSTS_DATA'
export const SET_POSTS = 'SET_POSTS'
export const SET_POSTS_META = 'SET_POSTS_META'
export const SET_POSTS_QUERIES = 'SET_POSTS_QUERIES'
export const CHANGE_ACTIVE_EDITING_LANGUAGE = 'CHANGE_ACTIVE_EDITING_LANGUAGE'
export const NEW_POST = 'NEW_POST'

//PAGES-TYPES
export const GET_PAGE_DATA = 'GET_PAGE_DATA'










