
export const INITIAL_POSTS = 'INITIAL_POSTS'

//USER TYPES
export const AUTO_LOGIN ='AUTO_LOGIN'
export const LOGIN ='LOGIN'
export const LOGOUT ='LOGOUT'
export const GET_SPECIFIC_USER_DATA ='GET_SPECIFIC_USER_DATA'
export const DISPATCH_SOCKET_ID ='SET_SOCKET_ID'
export const RESET_PASSWORD ='RESET_PASSWORD'
//messenger
export const GET_CONVERSATIONS ='GET_CONVERSATIONS'
export const GET_CONVERSATION ='GET_CONVERSATION'
export const NEW_MESSAGE_IN_CONVERSATION ='NEW_MESSAGE_IN_CONVERSATION'
//user page
export const SET_USER_PAGE_DATA= 'SET_USER_PAGE_DATA'
export const GET_USER_PAGE_DATA= 'GET_USER_PAGE_DATA'

//WIDGETS TYPES
export const SET_WIDGETS ='SET_WIDGETS'
export const SET_WIDGETS_FOR_ADMIN ='SET_WIDGETS_FOR_ADMIN'

//GLOBAL STATE TYPES
export const LOGIN_REGISTER_FORM ='LOGIN_REGISTER_FORM'
export const LOADING ='LOADING'
export const SET_ALERT ='SET_ALERT'
export const CLOSE_ALERT ='CLOSE_ALERT'
export const CHECK_ROUTE_AND_SET_LOADING= 'CHECK_ROUTE_AND_SET_LOADING'
export const HYDRATE ='HYDRATE'

//SETTINGS TYPES

export const GET_SETTINGS ='GET_SETTINGS'
export const SET_SETTINGS ='SET_SETTINGS'

//POSTS TYPES
export const GET_POSTS = 'GET_POSTS'
export const GET_POST = 'GET_POST'
export const SET_POST = 'SET_POST'
//comments
export const GET_COMMENTS = 'GET_COMMENTS'
export const NEW_COMMENT = 'NEW_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
//metas
export const SET_CATEGORIES_METAS = 'SET_CATEGORIES_METAS'
export const SET_TAGS_METAS = 'SET_TAGS_METAS'
export const SET_ACTORS_METAS = 'SET_ACTORS_METAS'

//CHATROOM ACTIONS TYPES
export const SET_ONLINE_USERS = 'SET_ONLINE_USERS'
export const SET_MESSAGES = 'SET_MESSAGES'
export const NEW_MESSAGE = 'NEW_MESSAGE'
export const SET_ACTIVE_VISIBLE_PROFILE = 'SET_ACTIVE_VISIBLE_PROFILE'

//POSTS PAGES TYPES
export const SET_POSTS_DATA = 'SET_POSTS_DATA'
export const SET_POSTS = 'SET_POSTS'
export const SET_POSTS_META = 'SET_POSTS_META'
export const SET_POSTS_QUERIES = 'SET_POSTS_QUERIES'


//ADMIN PANEL TYPES
export const GET_CUSTOM_PAGES = 'GET_CUSTOM_PAGES'
export const SAVE_NEW_WIDGET = 'SAVE_NEW_WIDGET'
export const UPDATE_WIDGET = 'UPDATE_WIDGET'
export const DELETE_WIDGET = 'DELETE_WIDGET'





