export interface FileManagerState {
    path: string,
    prevPath: string,
    files: [],
    clickedItem: string,
    clickedItemName: string,
    file: string,
    editFile: boolean,
    action: string,
    _do: string,
    // AlertBox:false,
    DeleteAlertBox: boolean,
    confirm:Date,
    message: string,
    report: string,
    inputBox: boolean,
    newItemName: string,
    lastUpdate:Date,
    createNewFileFolderPop:boolean,
    createNewFileFolderPopType:string,
    translationsData:string,
}