const languagesMapOrigin = {
    'en': 'English',
    'de': 'Deutsch',
    'ar': 'العربية',
    'da': 'Dansk',
    'el': 'Ελληνικά',
    'es': 'Español',
    'fa': 'فارسی',
    'fi': 'Suomi',
    'fr': 'Français',
    'hi': 'हिन्दी',
    'hu': 'Magyar',
    'it': 'Italiano',
    'ja': '日本語',
    'ko': '한국어',
    'nl': 'Nederlands',
    'no': 'Norsk',
    'pl': 'Polski',
    'pt': 'Português',
    'ru': 'Русский',
    'cs': 'Čeština',
    'sk': 'Slovenčina',
    'sl': 'Slovenščina',
    'sv': 'Svenska',
    'tr': 'Türkçe',
    'zh': '中文'
};

const languagesMapInEnglish = {
    'en': 'English',
    'de': 'German',
    'ar': 'Arabic',
    'da': 'Danish',
    'el': 'Greek',
    'es': 'Spanish',
    'fa': 'Persian',
    'fi': 'Finnish',
    'fr': 'French',
    'hi': 'Hindi',
    'hu': 'Hungarian',
    'it': 'Italian',
    'ja': 'Japanese',
    'ko': 'Korean',
    'nl': 'Dutch',
    'no': 'Norwegian',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'ru': 'Russian',
    'cs': 'Czech',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'sv': 'Swedish',
    'tr': 'Turkish',
    'zh': 'Chinese'
};

module.exports = {languagesMapInEnglish,languagesMapOrigin}