"use strict";
exports.__esModule = true;
exports.shouldCompress = exports.connectToDatabase = exports.mongoIdValidator = void 0;
// import fileDownloader from "./src/fileDownloader";
var mongoIdValidator_1 = require("./src/mongoIdValidator");
exports.mongoIdValidator = mongoIdValidator_1["default"];
var connectToDatabase_1 = require("./src/connectToDatabase");
exports.connectToDatabase = connectToDatabase_1["default"];
var shouldCompress_1 = require("./src/shouldCompress");
exports.shouldCompress = shouldCompress_1["default"];
