
//was generated by AI an edited
const sortArrayByPropertyOfObject = (array: any[], property: string, ascending: boolean) => {
    array.sort((a, b) => {
       return  a[property] < b[property] ?
                    ascending ? -1 : 1 :
               a[property] > b[property] ?
                   ascending ? 1 : -1 : 0
        // if (a[property] < b[property]) {
        //     return ascending ? -1 : 1;
        // } else if (a[property] > b[property]) {
        //     return ascending ? 1 : -1;
        // } else {
        //     return 0;
        // }
    });
}

export default sortArrayByPropertyOfObject