"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var express_1 = require("express");
var clientUsersRouter_1 = tslib_1.__importDefault(require("./clientUsersRouter"));
var clientSettingsRouter_1 = tslib_1.__importDefault(require("./clientSettingsRouter"));
var clientPostsRouter_1 = tslib_1.__importDefault(require("./clientPostsRouter"));
var clientWidgetsRouter_1 = tslib_1.__importDefault(require("./clientWidgetsRouter"));
var clientFileManagerRouter_1 = tslib_1.__importDefault(require("./clientFileManagerRouter"));
var clientPagesRouter_1 = tslib_1.__importDefault(require("./clientPagesRouter"));
var clientFormsRouter_1 = tslib_1.__importDefault(require("./clientFormsRouter"));
var clientOrdersRouter_1 = tslib_1.__importDefault(require("./clientOrdersRouter"));
var router = (0, express_1.Router)();
router.use('/users', clientUsersRouter_1.default);
router.use('/posts', clientPostsRouter_1.default);
router.use('/settings', clientSettingsRouter_1.default);
router.use('/widgets', clientWidgetsRouter_1.default);
router.use('/fileManager', clientFileManagerRouter_1.default);
router.use('/pages', clientPagesRouter_1.default);
router.use('/forms', clientFormsRouter_1.default);
router.use('/orders', clientOrdersRouter_1.default);
exports.default = router;
//# sourceMappingURL=clientMainRouter.js.map