"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var express_1 = require("express");
var authMiddleware_1 = tslib_1.__importDefault(require("../../middlewares/authMiddleware"));
var clientUpdateUserData_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientUpdateUserData"));
var clientRegisterNewUser_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientRegisterNewUser"));
var clientUserLogin_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientUserLogin"));
var clientResetUserPassword_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientResetUserPassword"));
var clientGetUserPreviewData_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientGetUserPreviewData"));
var clientGetMultipleUserDataById_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientGetMultipleUserDataById"));
var clientFollowUser_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientFollowUser"));
var clientUnFollowUser_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientUnFollowUser"));
var clientGetUserData_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientGetUserData"));
var clientGetSignedInUserData_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientGetSignedInUserData"));
var clientGetUsersList_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientGetUsersList"));
var clientSendMessage_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientSendMessage"));
var clientConversation_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientConversation"));
var clientMessageToConversation_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientMessageToConversation"));
var clientGetConversations_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientGetConversations"));
var clientGetConversation_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientGetConversation"));
var clientDeleteConversation_1 = tslib_1.__importDefault(require("./clientUsersControllers/clientDeleteConversation"));
var router = (0, express_1.Router)();
router.post('/register', clientRegisterNewUser_1.default);
router.post('/login', clientUserLogin_1.default);
router.post('/resetPassword', authMiddleware_1.default, clientResetUserPassword_1.default);
router.post('/getSignedInUserData', authMiddleware_1.default, clientGetSignedInUserData_1.default);
router.post('/getUserData', authMiddleware_1.default, clientGetUserData_1.default);
router.post('/updateUserData', authMiddleware_1.default, clientUpdateUserData_1.default);
router.post('/getUserPreviewData', clientGetUserPreviewData_1.default);
router.post('/getMultipleUserDataById', clientGetMultipleUserDataById_1.default);
router.post('/followUser', authMiddleware_1.default, clientFollowUser_1.default);
router.post('/unFollowUser', authMiddleware_1.default, clientUnFollowUser_1.default);
router.post('/getUsersList', clientGetUsersList_1.default);
router.post('/sendMessage', authMiddleware_1.default, clientSendMessage_1.default);
router.post('/conversation', authMiddleware_1.default, clientConversation_1.default);
router.post('/getConversations', authMiddleware_1.default, clientGetConversations_1.default);
router.post('/getConversation', authMiddleware_1.default, clientGetConversation_1.default);
router.get('/deleteConversation', authMiddleware_1.default, clientDeleteConversation_1.default);
router.post('/messageToConversation', authMiddleware_1.default, clientMessageToConversation_1.default);
exports.default = router;
//# sourceMappingURL=clientUsersRouter.js.map