"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var express_1 = require("express");
var authMiddleware_1 = tslib_1.__importDefault(require("../../middlewares/authMiddleware"));
var apiCache_1 = tslib_1.__importDefault(require("../../middlewares/apiCache"));
var clientGetPosts_1 = tslib_1.__importDefault(require("./clientPostsControllers/clientGetPosts"));
var clientGetPost_1 = tslib_1.__importDefault(require("./clientPostsControllers/clientGetPost"));
var clientLikeDislikeView_1 = tslib_1.__importDefault(require("./clientPostsControllers/clientLikeDislikeView"));
var clientNewComment_1 = tslib_1.__importDefault(require("./clientPostsControllers/clientNewComment"));
var clientCheckRemovedContent_1 = tslib_1.__importDefault(require("./clientPostsControllers/clientCheckRemovedContent"));
var clientGetMetas_1 = tslib_1.__importDefault(require("./clientPostsControllers/clientGetMetas"));
var clientGetMeta_1 = tslib_1.__importDefault(require("./clientPostsControllers/clientGetMeta"));
var clientGetComments_1 = tslib_1.__importDefault(require("./clientPostsControllers/clientGetComments"));
var clientUserCreateNewPost_1 = tslib_1.__importDefault(require("./clientPostsControllers/clientUserCreateNewPost"));
var clientUserUpdatePost_1 = tslib_1.__importDefault(require("./clientPostsControllers/clientUserUpdatePost"));
var clientFixMetaImage_1 = tslib_1.__importDefault(require("./clientPostsControllers/clientFixMetaImage"));
var ClientMetaSuggestion_1 = tslib_1.__importDefault(require("./clientPostsControllers/ClientMetaSuggestion"));
var router = (0, express_1.Router)();
router.get('/clientGetPosts', apiCache_1.default, clientGetPosts_1.default);
router.get('/clientGetPost', apiCache_1.default, clientGetPost_1.default);
router.get('/clientGetEditingPost', clientGetPost_1.default);
router.post('/likeDislikeView', clientLikeDislikeView_1.default);
router.post('/newComment', clientNewComment_1.default);
router.post('/checkRemovedContent', clientCheckRemovedContent_1.default);
router.post('/fixMetaImage', clientFixMetaImage_1.default);
router.get('/getMetas', apiCache_1.default, clientGetMetas_1.default);
router.get('/getMeta', apiCache_1.default, clientGetMeta_1.default);
router.get('/getComments', clientGetComments_1.default);
router.post('/userCreateNewPost', authMiddleware_1.default, clientUserCreateNewPost_1.default);
router.post('/userUpdatePost', authMiddleware_1.default, clientUserUpdatePost_1.default);
router.get('/metaSuggestion', ClientMetaSuggestion_1.default);
exports.default = router;
//# sourceMappingURL=clientPostsRouter.js.map