const widgetsTypes  = [
    'text',
    'advertise',
    'textEditor',
    'menu',
    'linkTo',
    'dayModeNightMode',
    'multipleLinkTo',
    'posts',
    'media',
    'searchbar',
    'meta',
    'metaWithImage',
    'logo',
    'form',
    'shoppingCart',
    'alphabeticalNumericalRange',
    'language',
    'authentication',
    'imagesSlider',
    'postsSwiper',
    // 'recentComments',
    'postsSlider',
]

export default widgetsTypes