const widgetsTypes = [
    'text',
    'advertise',
    'textEditor',
    'menu',
    'linkTo',
    'dayModeNightMode',
    'multipleLinkTo',
    'posts',
    'media',
    'recentComments',
    'searchBar',
    'searchButton',
    'meta',
    'metaWithImage',
    'logo',
    'form',
    'shoppingCart',
    'alphabeticalNumericalRange',
    'language',
    'authentication',
    'postsSlider',
    'imageSwiper',
    'postsSwiper',
]

export default widgetsTypes